image: docker:latest
services:
 - docker:dind

stages:
 - deploy

step-backend:
 stage: deploy
 script:
  - apt-get install -y python-pip
  - pip install docker-compose
  - docker-compose -f Project/docker-compose.yml build --no-cache
  - docker-compose -f Project/docker-compose.yml up -d
