image: docker:latest
services:
 - docker:dind

default:
  before_script:
    - docker kill $(docker ps -q)
    - docker rm $(docker ps -aq)

stages:
 - deploy

deploy-backend:
 stage: deploy
 script:
  - docker build --tag "backend" Project/Backend
  - docker run -p 8000:8000 -d backend

deploy-frontend:
 stage: deploy
 script:
  - docker build --tag "frontend" Project/Frontend/Mapper
  - docker run -p 8800:80 -d frontend
  
