image: docker:latest
services:
 - docker:dind

stages:
 - deploy

before_script:
  - apk update -qq && apk add -y -qq py-pip

step-backend:
 stage: deploy
 script:
  - pip install docker-compose
  - docker-compose -f Project/docker-compose.yml build --no-cache
  - docker-compose -f Project/docker-compose.yml up -d
