image: docker:latest
services:
 - docker:dind

stages:
 - deploy

before-script:
  - apt-get update -qq && apt-get install -y -qq python-pip

step-backend:
 stage: deploy
 script:
  - pip install docker-compose
  - docker-compose -f Project/docker-compose.yml build --no-cache
  - docker-compose -f Project/docker-compose.yml up -d
