image: docker:latest
services:
  - docker:dind

stages:
  - cleanup
  - deploy

clean-dockers:
  stage: cleanup
  script:
    - docker ps -aq
    - docker kill $(docker ps -aq) || true
    - docker rm $(docker ps -aq) || true
    - docker volume ls -qf dangling=true
    - docker volume rm $(docker volume ls -qf dangling=true) || true
    - docker rmi $(docker image ls) || true
  only:
    - master
    - docker

deploy-backend-frontend:
  stage: deploy
  script:
    - docker build --tag "frontend" Project/Frontend/Mapper
    - docker run -p 8800:80 -d frontend
    - docker build --tag "backend" Project/Backend
    - docker run -p 8000:8000 -d backend

  only:
    - master
    - docker
