image: docker:latest
services:
 - docker:dind

stages:
 - build
 - deploy

build-backend:
 stage: build
 script:
  - docker build --tag "backend" Project/Backend

build-frontend:
 stage: build
 script:
  - docker build --tag "frontend" Project/Frontend/Mapper

deploy-backend:
 stage: deploy
 script:
  - docker run -p 8000:8000 backend -d

deploy-frontend:
 stage: deploy
 script:
  - docker run -p 8800:80 frontend -d
  
