# Generated by Django 2.2.6 on 2019-11-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_cars', models.IntegerField()),
                ('actual_direction', models.BooleanField()),
                ('accident', models.IntegerField()),
                ('beggining_coords_x', models.IntegerField()),
                ('beggining_coords_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficJammer.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('begin_coord_x', models.IntegerField()),
                ('begin_coord_y', models.IntegerField()),
                ('ending_coord_x', models.IntegerField()),
                ('ending_coord_y', models.IntegerField()),
                ('length', models.IntegerField()),
                ('connect_to', models.ManyToManyField(blank=True, related_name='_street_connect_to_+', to='TrafficJammer.Street')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficJammer.Street'),
        ),
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
                ('date', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficJammer.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('street', 'beggining_coords_x', 'beggining_coords_y', 'actual_direction')},
        ),
    ]
