# Generated by Django 2.2.6 on 2019-12-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficJammer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=6)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrafficJammer.Section')),
            ],
        ),
    ]
