# Generated by Django 2.2.6 on 2019-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficJammer', '0003_auto_20191202_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='police',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='roadblock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='visibility',
            field=models.IntegerField(default=100),
        ),
    ]
