# Generated by Django 2.2.6 on 2019-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficJammer', '0007_auto_20191202_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='police',
            field=models.BooleanField(default=False),
        ),
    ]
